apiVersion: v1
kind: Pod
metadata:
  name: todoapp
  namespace: todoapp
  labels:
    app: todoapp
spec:
  containers:
  - name: todolist
    image: ikulyk404/todoapp:3.0.0
    imagePullPolicy: Always
    env:
    - name: DEBUG
      value: "False"
    - name: SECRET_KEY
      value: "you-secret-key"
    ports:
    - containerPort: 8080
    livenessProbe:
      httpGet:
        path: api/health
        port: 8080
      initialDelaySeconds: 60
      periodSeconds: 5
    readinessProbe:
      httpGet:
        path: api/ready
        port: 8080
      initialDelaySeconds: 5
      periodSeconds: 5

---

apiVersion: v1
kind: Pod
metadata:
  name: todoapp-1
  namespace: todoapp
  labels:
    app: todoapp
spec:
  containers:
  - name: todolist
    image: ikulyk404/todoapp:3.0.0
    imagePullPolicy: Always
    env:
    - name: DEBUG
      value: "False"
    - name: SECRET_KEY
      value: "you-secret-key"
    ports:
    - containerPort: 8080
    livenessProbe:
      httpGet:
        path: api/health
        port: 8080
      initialDelaySeconds: 60
      periodSeconds: 5
    readinessProbe:
      httpGet:
        path: api/ready
        port: 8080
      initialDelaySeconds: 5
      periodSeconds: 5
